name: DevSecOps CI/CD - Flutter App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  flutter-security:
    name: Audit sécurité Flutter (analyze, test, secrets, deps)
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      - name: Installer Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'  # Dart 3.5.4 inclus

      - name: Vérifier la version Flutter
        run: flutter --version

      - name: Installer les dépendances
        run: flutter pub get

      - name: Analyse statique du code
        run: flutter analyze > flutter-analyze-report.txt || true

      - name: Exécuter les tests unitaires
        run: flutter test --machine > flutter-test-report.json || true

      - name: Scan des secrets (Gitleaks)
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          ./gitleaks detect --source . --report-path=gitleaks-report.json || true

      - name: Audit des dépendances (pubspec_audit)
        run: |
          dart pub global activate pubspec_audit
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          pubspec_audit --json > pubspec-audit-report.json || true

      - name: Upload des rapports
        uses: actions/upload-artifact@v4
        with:
          name: rapports-devsecops-flutter
          path: |
            flutter-analyze-report.txt
            flutter-test-report.json
            gitleaks-report.json
            pubspec-audit-report.json
